name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.2.4
  dart_jsonwebtoken: ^3.3.0
  dotenv: ^4.2.0
  http: ^1.5.0
  postgres: ^3.5.7
  
dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
